name: docker-build-and-push
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/futurezero-split_test:latest , ${{ secrets.DOCKER_USERNAME }}/futurezero-split_test:main
          build-args: |
            NEXT_PUBLIC_TEST_A=${{ secrets.NEXT_PUBLIC_TEST_A }}
            NEXT_PUBLIC_TEST_B=${{ secrets.NEXT_PUBLIC_TEST_B }}
            NEXT_PUBLIC_TEST_C=${{ secrets.NEXT_PUBLIC_TEST_C }}
            NEXT_PUBLIC_TOS=${{ secrets.NEXT_PUBLIC_TOS }}
            NEXT_PUBLIC_GOOGLE_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_ID }}      